# 前后端分为两个服务，前端服务端口为 8799，后端服务端口为 8848

version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8848:8848"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8799:8799"
